# Generated by Django 5.1 on 2025-01-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='loan_ac_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
