# Generated by Django 5.1 on 2024-12-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.technician'),
        ),
    ]
