# Generated by Django 5.1 on 2024-12-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0002_alter_purchase_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
