# Generated by Django 5.1 on 2025-01-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0002_emi_loan_ac_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi',
            old_name='loan_ac_no',
            new_name='loan_account_no',
        ),
    ]
