# Generated by Django 5.1 on 2024-12-13 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0003_jobcard_driver_alter_jobcard_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='jobcarditem',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
