# Generated by Django 5.1 on 2024-12-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0003_emi_frequency_emi_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi_item',
            name='installment_date',
            field=models.DateField(null=True),
        ),
    ]
