# Generated by Django 5.1 on 2025-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0003_remove_breakdown_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
