# Generated by Django 5.1 on 2024-12-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_emi_item_installment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending EMI'), ('closed', 'Closed EMI')], default='pending', max_length=20),
        ),
    ]
