# Generated by Django 5.1 on 2025-02-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_purchase_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_fuel',
            field=models.BooleanField(default=False),
        ),
    ]
