# Generated by Django 5.1 on 2025-01-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_alter_emi_finance_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetaxdue',
            name='insurance_name',
        ),
        migrations.AlterField(
            model_name='insurancetaxdue',
            name='insurance_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.insurance_bank'),
        ),
    ]
