# Generated by Django 5.1 on 2024-12-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_remove_jobcard_total_cost_jobcarditem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='completed_status',
            new_name='status',
        ),
    ]
