# Generated by Django 5.1 on 2024-12-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0004_jobcard_closing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='closing_date',
            new_name='completed_date',
        ),
    ]
