# Generated by Django 5.1 on 2024-12-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_rename_completed_status_jobcard_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='job_date',
            new_name='date',
        ),
    ]
