# Generated by Django 5.1 on 2024-12-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_rename_closing_date_jobcard_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
