# Generated by Django 5.1 on 2025-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_customuser_is_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
