# Generated by Django 5.1 on 2024-12-31 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0005_emi_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateDriverToVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date_time', models.DateTimeField(auto_now_add=True)),
                ('leaving_date_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.driver')),
                ('vahicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.vehicle')),
            ],
        ),
    ]
