# Generated by Django 5.1 on 2024-12-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0006_alter_jobcard_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
