# Generated by Django 5.1 on 2025-03-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0006_alter_breakdown_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
