# Generated by Django 5.1 on 2025-02-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0006_alter_emi_next_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate in percentage', max_digits=5, null=True),
        ),
    ]
