# Generated by Django 5.1 on 2025-03-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0007_alter_breakdown_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedrivertovehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_drivers', to='ERP_Admin.driver'),
        ),
    ]
