# Generated by Django 5.1 on 2025-01-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0007_customuser_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceTaxDue',
        ),
    ]
