# Generated by Django 5.1 on 2024-12-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0008_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='emp_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.emp_id'),
        ),
    ]
