# Generated by Django 5.1 on 2025-02-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0008_emi_installment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi_installment',
            name='installment_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
