# Generated by Django 5.1 on 2025-03-07 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0008_alter_allocatedrivertovehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedrivertovehicle',
            name='driver',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='allocated_drivers', to='ERP_Admin.driver'),
            preserve_default=False,
        ),
    ]
