# Generated by Django 5.1 on 2025-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0009_emi_installment_installment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='total_installments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='emi_installment',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
