# Generated by Django 5.1 on 2025-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0010_alter_emi_total_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
