# Generated by Django 5.1 on 2025-02-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0011_alter_emi_total_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='total_installments',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
