# Generated by Django 5.1 on 2025-03-07 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0011_alter_allocatedrivertovehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.driver'),
        ),
    ]
