# Generated by Django 5.1 on 2025-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0012_alter_emi_total_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedrivertovehicle',
            name='leaving_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
