# Generated by Django 5.1 on 2024-12-15 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0012_alter_customuser_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.emp_id'),
        ),
    ]
