# Generated by Django 5.1 on 2025-02-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0013_alter_allocatedrivertovehicle_leaving_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
