# Generated by Django 5.1 on 2024-12-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0013_technician_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
