# Generated by Django 5.1 on 2024-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0014_alter_product_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='Documents'),
        ),
    ]
