# Generated by Django 5.1 on 2025-02-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0015_alter_allocatedrivertovehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Breakdown_Audio'),
        ),
    ]
