# Generated by Django 5.1 on 2025-02-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0013_alter_otherdues_fitness_document_and_more'),
        ('ERP_Admin', '0016_alter_breakdown_audio'),
    ]

    operations = [
    ]
