# Generated by Django 5.1 on 2024-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0016_alter_driver_adhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
