# Generated by Django 5.1 on 2025-02-12 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0016_alter_breakdown_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_type', to='ERP_Admin.breakdowntype'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_vehicle', to='ERP_Admin.vehicle'),
        ),
    ]
