# Generated by Django 5.1 on 2024-12-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0017_alter_driver_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='emp_id',
        ),
    ]
