# Generated by Django 5.1 on 2025-02-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0017_merge_20250213_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_type', to='ERP_Admin.breakdowntype'),
        ),
        migrations.AlterField(
            model_name='breakdown',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_vehicle', to='ERP_Admin.vehicle'),
        ),
        migrations.CreateModel(
            name='FuelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_km', models.PositiveIntegerField()),
                ('last_fuel_date', models.DateField(blank=True, null=True)),
                ('current_km', models.PositiveIntegerField()),
                ('dashboard_photo', models.ImageField(blank=True, null=True, upload_to='fuel/dashboard_photos/')),
                ('dispenser_photo', models.ImageField(blank=True, null=True, upload_to='fuel/dispenser_photos/')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='fuel/receipt_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.vehicle')),
            ],
        ),
    ]
