# Generated by Django 5.1 on 2025-02-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0018_alter_breakdown_type_alter_breakdown_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrecord',
            name='last_fuel_date',
        ),
        migrations.RemoveField(
            model_name='fuelrecord',
            name='last_km',
        ),
    ]
