# Generated by Django 5.1 on 2025-02-16 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0019_remove_fuelrecord_last_fuel_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_driver', to='ERP_Admin.driver'),
        ),
    ]
