# Generated by Django 5.1 on 2025-02-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Admin', '0020_breakdown_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ERP_Admin.driver'),
        ),
    ]
